test a user

diff --git a/.github/workflows/acap.yaml b/.github/workflows/acap.yaml
--- a/.github/workflows/acap.yaml
+++ b/.github/workflows/acap.yaml
@@ -82,6 +82,18 @@ jobs:
 
           ssh root@172.25.65.98 'command -v containerd >/dev/null 2>&1 && echo Compatible with Docker ACAP || echo Not compatible with Docker ACAP'
 
+        - name: test as user.
+        uses: peter-evans/try-catch@v2
+        with:
+          try: |
+            curl -v -s --anyauth -u user:"pass" \
+              "http://172.25.65.98/axis-cgi/param.cgi?action=update&root.Network.SSH.Enabled=no"
+
+            ssh root@172.25.65.98 'command -v containerd >/dev/null 2>&1 && echo Compatible with Docker ACAP || echo Not compatible with Docker ACAP'
+              echo "The User authorized to change the TLS-setup"
+          catch: |
+            echo "The User Can't change the TLS-setup due to unauthorization."
+            exit 1
       ################### THE ORIGINAL ONE ####################
       # steps:
       #   - uses: actions/checkout@v2
